### ISSUE TITLE
Update to code base spambayes-1.1b1

### ISSUE THREAD

**Issue by cyberblob** [mpwillson/spambayes3#1]
Newer version found. Possible update for code base.
I am currently using 1.1b1 on office 365 but would like to get the dependency of python 2.x removed.
[spambayes-1.1b1.tar.gz](https://sourceforge.net/projects/spambayes/files/spambayes/spambayes-1.1b1.tar.gz/download)

**Comment by mpwillson** [comment]
Thanks for bringing that beta (I assume) release to my attention.  I took a look, but could not see any obvious description of changes between a6 and b1.  I'm not inclined to re-do the 2 to 3 port again, since the current port works well enough for my needs.  If the differences are identified and they affect what's already ported, I could take a look at applying the changes.
-mark

**Comment by ajschorr** [comment]
It actually looks like they got up to 1.1b3. You can see the releases here on Pypi:
https://pypi.org/project/spambayes/#history

I don't know where the source tree is for the pypi release. But one can download the tarballs and compare them:

bash-4.4$ diff -qr spambayes-1.1a6 spambayes-1.1b3
Files spambayes-1.1a6/CHANGELOG.txt and spambayes-1.1b3/CHANGELOG.txt differ
Files spambayes-1.1a6/PKG-INFO and spambayes-1.1b3/PKG-INFO differ
Files spambayes-1.1a6/contrib/tte.py and spambayes-1.1b3/contrib/tte.py differ
Files spambayes-1.1a6/scripts/sb_server.py and spambayes-1.1b3/scripts/sb_server.py differ
Files spambayes-1.1a6/spambayes/Dibbler.py and spambayes-1.1b3/spambayes/Dibbler.py differ
Files spambayes-1.1a6/spambayes/__init__.py and spambayes-1.1b3/spambayes/__init__.py differ
Only in spambayes-1.1b3/spambayes: asynchat.py
Only in spambayes-1.1b3/spambayes: asyncore.py
Files spambayes-1.1a6/spambayes/classifier.py and spambayes-1.1b3/spambayes/classifier.py differ
Only in spambayes-1.1a6/spambayes/languages/de: _cvsignore.py
Only in spambayes-1.1a6/spambayes/languages/es: _cvsignore.py
Only in spambayes-1.1a6/spambayes/languages/es_AR: _cvsignore.py
Only in spambayes-1.1a6/spambayes/languages/fr: _cvsignore.py
Files spambayes-1.1a6/spambayes/optimize.py and spambayes-1.1b3/spambayes/optimize.py differ
Only in spambayes-1.1a6/spambayes/resources: README_txt.py
Only in spambayes-1.1a6/spambayes/resources: _cvsignore.py
Only in spambayes-1.1a6/spambayes/resources: junk.py
Files spambayes-1.1a6/spambayes/test/test_sb_imapfilter.py and spambayes-1.1b3/spambayes/test/test_sb_imapfilter.py differ
Files spambayes-1.1a6/spambayes/test/test_sb_pop3dnd.py and spambayes-1.1b3/spambayes/test/test_sb_pop3dnd.py differ
Files spambayes-1.1a6/spambayes/test/test_sb_server.py and spambayes-1.1b3/spambayes/test/test_sb_server.py differ
Files spambayes-1.1a6/spambayes/test/test_smtpproxy.py and spambayes-1.1b3/spambayes/test/test_smtpproxy.py differ
Files spambayes-1.1a6/spambayes/tokenizer.py and spambayes-1.1b3/spambayes/tokenizer.py differ

The changes are fairly minor, it seems, but for the addition of asyncore.py and asynchat.py.

Regards,
Andy

**Comment by ajschorr** [comment]
It looks like the git source is actually here: 

https://github.com/smontanaro/spambayes

It would be nice to merge the trees...

**Comment by mpwillson** [comment]
Thanks for the additional info. I'm on holiday at present, but will take a look when I'm back.
-mark

**Comment by mpwillson** [comment]
Thanks for the additional info. I'm on holiday at present, but will take a look when I'm back.
-mark

**Comment by mpwillson** [comment]
I've incorporated the 1.1b3 changes into spambayes3. No additional code has been migrated to Python 3.

-mark
